### PR TITLE
Update co_hook_sys_call.cpp

### PR DESCRIPTION
**Pull request by wutaowater0107**
add pthread_setspecific and pthread_getspecific hook function, througth testing, we can make more thread data into cortinue data. and that is apllyed to our project.

### CODE REVIEW

**Comment by leiffyli** [comment]
@wutaowater0107 hi,wutao.  We don't think it's a good idea that replace a thread specific variable into a coroutine specific  variable.  Thread specific variable has it's own semantics in multithread environment.  We won't change the system default behavior while it may cause an unexpected result.

**Comment by wutaowater0107** [comment]
@leiffyli  The most of old code had thread specific variable in multithread  program,  if i want to change to coroutine program, i think its hook is a good way .  at the same time ,  this modifation has been applied to our project, and is working well.  which may be an unexpected result  ?  please give me example.

**Comment by leiffyli** [comment]
We want the coroutine specific variable to be a clear behavior. If replace all the thread specific variable into coroutine specific,  it may has following two questions:
1, There is no way to define a thread specific that is thread specific but coroutine shared. For example, we want to do thread-level statistics,  clearly that we only need the thread specific variables.
2, The implementation of the pthread specific hook is usually not expected in our project.  The number of coroutines  is usually far more than the number of threads. This hook replacement may result in additional memory used for the system.

**Comment by wutaowater0107** [comment]
@leiffyli  somtimes or in some expected case ,  the two questions are examples which have some unexpected result 。that's like read & write socket functions hook  which can't apply to any case。so i think hook system call has some limitations，not universal， do you agree with me ?

**Comment by leiffyli** [comment]
@wutaowater0107 Correctly. In our opinion, we always treat the system api hook carefully. Like read & write socket functions, we just delay the api excute  to the right right time when it's happening by coroutine yield and resume.  We don't wan't to change the system default behavior as much as possible. Thank you for your feedback. :)

**Pull request closed without merging**
